[project]
title = "Tuition Explorer"
version = "1.0.0"
port = 8501
slug = "tuition-explorer"
entrypoint = "tuitionanalysis.py"

[branding]
name = "Tuition Insights"
logo = "images/tuition.png"
favicon = "images/favicontuition.ico"
primaryColor = "#1E90FF"

[data.studentcost_csv]
type = "csv"
path = "data/studentcost.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
